// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";

export type FileInfo = { path: string, size: bigint, contentHash: string, assetKind: AssetKind, lockOwner: string | null, };
