// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoInfo = { name: string, description: string | null, default_branch: string, };
