// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RevisionInfo = { id: string, parent_ids: Array<string>, author: string, message: string, timestamp: bigint, };
