// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileState } from "./FileState";

export type StatusEntry = { path: string, state: FileState, };
