// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type TreeEntry = { name: string, path: string, kind: EntryKind, size: bigint | null, contentHash: string | null, };
